export enum Rule {
  EMPTY = 'EMPTY',
  NOT_EMPTY = 'NOT_EMPTY',
  EQUAL = 'EQUAL',
  NOT_EQUAL = 'NOT_EQUAL',
  STARTS_WITH = 'STARTS_WITH',
  ENDS_WITH = 'ENDS_WITH',
  INCLUDES = 'INCLUDES',
  CONTAINS_ANY = 'CONTAINS_ANY',
  CONTAINS_ALL = 'CONTAINS_ALL',
  NOT_CONTAINS_ANY = 'NOT_CONTAINS_ANY',
  NOT_CONTAINS_ALL = 'NOT_CONTAINS_ALL',
  HIGHER = 'HIGHER',
  HIGHER_OR_EQUAL = 'HIGHER_OR_EQUAL',
  LOWER = 'LOWER',
  LOWER_OR_EQUAL = 'LOWER_OR_EQUAL',
  IN = 'IN',
  NOT_IN = 'NOT_IN',
  IS_TRUE = 'IS_TRUE',
  IS_FALSE = 'IS_FALSE',
}

export enum Operator {
  AND = 'AND',
  OR = 'OR',
}
